import { PERMISSIONS } from "../utils/constant.js";
const permissions = {
  user: [
    PERMISSIONS.REGISTER_EVENT,
  ],

  organizer: [
    PERMISSIONS.REGISTER_EVENT,
    PERMISSIONS.CREATE_EVENT,
    PERMISSIONS.EDIT_OWN_EVENT,
    PERMISSIONS.DELETE_OWN_EVENT,
    PERMISSIONS.VIEW_ATTENDEES,
  ],
  organizer_temp:[
    PERMISSIONS.CREATE_EVENT,
  ],

  admin: [
    PERMISSIONS.REGISTER_EVENT,
    // PERMISSIONS.CREATE_EVENT, // intentionally disabled
    PERMISSIONS.EDIT_OWN_EVENT,
    PERMISSIONS.DELETE_OWN_EVENT,
    PERMISSIONS.VIEW_ATTENDEES,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.APPROVE_EVENT,
    PERMISSIONS.APPROVE_ORGANIZERS,
    PERMISSIONS.SYSTEM_SETTINGS,
  ],
};

export default permissions;