// permissions
export const PERMISSIONS = {
  REGISTER_EVENT: "REGISTER_EVENT",
  CREATE_EVENT: "CREATE_EVENT",
  EDIT_OWN_EVENT: "EDIT_OWN_EVENT",
  DELETE_OWN_EVENT: "DELETE_OWN_EVENT",
  VIEW_ATTENDEES: "VIEW_ATTENDEES",
  MANAGE_USERS: "MANAGE_USERS",
  APPROVE_EVENT: "APPROVE_EVENT",
  APPROVE_ORGANIZERS: "APPROVE_ORGANIZERS",
  SYSTEM_SETTINGS: "SYSTEM_SETTINGS",
};
